### ISSUE TITLE
About Rabbit4Mt4

### ISSUE THREAD

**Issue by femtotrader** [OpenTrading/OTMql4AMQP#1]
Hi,

I saw
https://github.com/OpenTrading/OTMql4AMQP/wiki/Rabbit4Mt4

I'm also doing a round trip

see https://www.youtube.com/watch?v=2CFt9tGjD8M

https://github.com/femtotrader/rabbit4mt4/blob/master/emit/MQL4/Experts/rabbit4mt4_execute_rpc.mq4

```
while(true)
 {
  if((TimeLocal()-prev_time)>=1) //Do stuff once per second
    {
     prev_time=TimeLocal();

     get_json_rpc_from_db(g_db_connect_id,g_terminal_id_setting);

    }

  Sleep(g_sleep_ms);
 }
```

**Comment by femtotrader** [comment]
You might see 
https://github.com/femtotrader/rabbit4mt4/blob/master/drawings/drawing.png

**Comment by OpenTrading** [comment]
That's polling the AMQP, but I am doubly polling: once to run the Python thread, and a second time to pull the result from Python up to Mt4.

Is your AMQP working now? What I was getting at in the wiki page is that if you wired your APQP up to recognize the message format I'm using, with the ProcessCmd to dispatch the result, then I could talk to your AMQP directly, without pika under Python under Mt4. It would get rid of Python in the middle, which would make it easier for people to use, or for me be shrink-wrap it.

You might think of moving the body of your polling to an OnTimer event, so that your users could control the polling interval by controling the Timer: see iTIMER_INTERVAL_SEC in OTPyTestPikaEA.mq4.

**Comment by femtotrader** [comment]
What I don't like in my solution is the need of MySQL database.

**Comment by OpenTrading** [comment]
That should just be a matter of refactoring the code. If your Mt4AMQP is listening for commands from my pika client, and taking the string that it receives and processing it with my *ProcessCmd.mq4 functions, and replying with the result in my format, it's shouldn't need and SQL database. Can you not refactor out the MySQL dependency? If I'm just asking for AccountBalance, there's no need for a database in the execution path.

Similarly if you're just publishing the bar info in my format for my pika to subscribe to?

**Comment by OpenTrading** [comment]
We've now got OTMql4Zmq working to communicate with  Mt4, with or without Python,
so it will be easier to shrink-wrap a binary distribution that does not require a Python
on the end-users machine. So we won't look much more at AMQP, as ZeroMQ is much faster.

OpenTrader will use that as soon as we have OTMql4Zmq in a distributable binary: Real Soon Now.
